const { withAndroidManifest } = require('@expo/config-plugins');

/**
 * Custom plugin to fix the malformed Android Manifest generated by expo-share-intent.
 * It manually adds the SEND intent filter with the correct mimeType string
 * to avoid the "[object Object]" serialization error and ensures singleTask mode.
 */
module.exports = function withAndroidShareIntentFix(config) {
  return withAndroidManifest(config, (config) => {
    const mainActivity =
      config.modResults.manifest.application[0].activity.find(
        (a) => a.$['android:name'] === '.MainActivity'
      );

    if (mainActivity) {
      // Force singleTask to ensure the app instance is reused
      mainActivity.$['android:launchMode'] = 'singleTask';

      // Clear existing SEND intent filters to avoid malformed [object Object]
      if (mainActivity['intent-filter']) {
        mainActivity['intent-filter'] = mainActivity['intent-filter'].filter(
          (filter) => {
            const hasSendAction = filter.action?.some(
              (action) =>
                action.$['android:name'] === 'android.intent.action.SEND'
            );
            return !hasSendAction;
          }
        );
      }

      // Re-inject clean intent filters
      mainActivity['intent-filter'].push({
        action: [{ $: { 'android:name': 'android.intent.action.SEND' } }],
        category: [
          { $: { 'android:name': 'android.intent.category.DEFAULT' } }
        ],
        data: [{ $: { 'android:mimeType': 'text/plain' } }]
      });
    }

    return config;
  });
};
